language: go

install:
  - mkdir -p ~/bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz -o hugo.tgz
  - tar xfv hugo.tgz -C ~/bin
  - rm hugo.tgz ~/bin/*.md
  - export PATH=$HOME/bin:$PATH

script:
  - go get github.com/kardianos/govendor
  - govendor get github.com/gohugoio/hugo
  - go install github.com/gohugoio/hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $787435936f1d4b4d342b84e4a486564199ab73a9
  local_dir: $hugo-ntpsec
  target_branch: gh-pages
  on:
    branch: master
