language: go

install:
  - mkdir -p ~/bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz -o hugo.tgz
  - tar xfv hugo.tgz -C ~/bin
  - rm hugo.tgz ~/bin/*.md
  - export PATH=$HOME/bin:$PATH

script:
  - hugo import jekyll jekyll_root_path target_path

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $787435936f1d4b4d342b84e4a486564199ab73a9
  local_dir: $TRAVIS_BUILD_DIR/hugo-ntpsec
  target_branch: gh-pages
  on:
    branch: master
